FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install langchain-groq langchain-huggingface sentence-transformers

COPY app/ ./app/

WORKDIR /app/app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.host", "0.0.0.0", "--server.port", "8501"]